"use client";

// Icon Park Outline icon re-exports (verified against @icon-park/react exports).
export {
  Home as IconHome,
  Briefcase as IconBriefcase,
  Calendar as IconCalendar,
  PaperMoney as IconMoney,
  Dollar as IconDollar,
  Brightness as IconIdea,         // ideas
  Notes as IconNotes,
  Plug as IconPlug,               // integrations
  Setting as IconSettings,
  Plus as IconPlus,
  Add as IconAdd,
  Close as IconClose,
  CloseSmall as IconCloseSmall,
  Right as IconRight,
  Left as IconLeft,
  Down as IconDown,
  Up as IconUp,
  ArrowRight as IconArrowRight,
  ArrowLeft as IconArrowLeft,
  ArrowUp as IconArrowUp,
  ArrowDown as IconArrowDown,
  Check as IconCheck,
  CheckSmall as IconCheckSmall,
  Correct as IconCorrect,
  More as IconMore,
  Edit as IconEdit,
  Delete as IconDelete,
  Link as IconLink,
  Eyes as IconEye,                // view
  PreviewClose as IconEyeInvisible,
  Search as IconSearch,
  Star as IconStar,
  Magic as IconAuto,            // AI auto-filled marker
  Upload as IconUpload,
  Download as IconDownload,
  Paperclip as IconPaperclip,
  Shopping as IconShopping,
  Trend as IconTrend,
  Inbox as IconMail,
  Wallet as IconWallet,
  Credit as IconCredit,
  Gift as IconGift,
  Send as IconSend,
  ViewGridCard as IconGrid,
  List as IconList,
  Filter as IconFilter,
  Refresh as IconRefresh,
  Remind as IconRemind,
  Caution as IconWarning,
  Info as IconInfo,
  CheckOne as IconSuccess,
  Error as IconError,
  MenuFold as IconMenu,
  Logout as IconLogout,
  User as IconUser,
  Crown as IconCrown,
  Lock as IconLock,
  Creative as IconPalette,        // theming
  Drag as IconDrag,
  Music as IconMusic,
  Video as IconVideo,
  FileAddition as IconFile,
  ListTop as IconSort,
} from "@icon-park/react";
export { IconProvider } from "@icon-park/react";
